# -*- coding: utf-8 -*-
"""Ecom_sys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCR9IGOIpfXWpi2YhTurN7Tut4oRIZlZ

**Ecommerce Recommendation System**
"""

#pip install streamlit mlxtend pandas matplotlib

#!pip install mlxtend

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

st.title("🛒 E-Commerce Recommendation System")

# Dataset
transactions = [
    ['Laptop','Mouse','Keyboard'],
    ['Laptop','Mouse'],
    ['Laptop','Bag'],
    ['Mouse','Keyboard'],
    ['Laptop','Mouse','Bag'],
    ['Laptop','Keyboard'],
    ['Mouse','Keyboard'],
    ['Laptop','Mouse','Keyboard','Bag']
]

# Encoding
te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_data, columns=te.columns_)

# Apriori
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

# ✅ IMPORTANT: Generate Rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

# 🔹 Recommendation Function
def recommend(product):
    if rules.empty:
        return []
    
    rec = rules[rules['antecedents'].apply(lambda x: product in list(x))]
    
    if rec.empty:
        return []
    
    rec = rec.sort_values(by='confidence', ascending=False)
    
    recommendations = []
    for i in rec['consequents']:
        for item in list(i):
            recommendations.append(item)
    
    return list(set(recommendations))

# 🔹 UI Input
product = st.selectbox("Select Product", df.columns)

if st.button("Get Recommendation"):
    result = recommend(product)
    if result:
        st.success(f"Recommended items for {product}: {result}")
    else:
        st.warning("No strong recommendations found")

# ⭐ Graph: Item Frequency
st.subheader("📊 Item Frequency")
item_counts = df.sum().sort_values(ascending=False)

plt.figure()
item_counts.plot(kind='bar')
plt.xlabel("Items")
plt.ylabel("Frequency")
st.pyplot(plt)

# ⭐ Graph: Support Values
st.subheader("📊 Frequent Itemsets Support")

plt.figure()
plt.bar(range(len(frequent_itemsets)), frequent_itemsets['support'])
plt.xlabel("Itemsets Index")
plt.ylabel("Support")
st.pyplot(plt)

# ⭐ Show Data
if st.checkbox("Show Frequent Itemsets"):
    st.write(frequent_itemsets)

if st.checkbox("Show Association Rules"):
    st.write(rules)
